# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmPeXZ0mvmAItSq1Pvc6ahObjtTRMSOZ
"""

import streamlit as st
from PIL import Image


# Page Configuration

st.set_page_config(
    page_title="Air Quality Analytics Platform",
    layout="wide")


# Header

image = Image.open("images.jpeg")
image = image.resize((1200, 250))
st.image(image, use_container_width=True)

st.title("Air Quality Analytics & Prediction System")


# Sidebar Navigation

page = st.sidebar.radio(
    "Navigate",
    [
        "Data Overview",
        "Exploratory Data Analysis (EDA)",
        "Modelling & Prediction" ])


# Page Routing

if page == "Data Overview":
    from pages.data_overview import show_data_overview
    show_data_overview()

elif page == "Exploratory Data Analysis (EDA)":
    from pages.eda import show_eda
    show_eda()

elif page == "Modelling & Prediction":
    from pages.modelling import show_modelling
    show_modelling()