# -*- coding: utf-8 -*-
"""data_overview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qafn3HegUKdFx8raIcKuVlD11fp3zAbB
"""

import streamlit as st
import pandas as pd

@st.cache_data
def load_data():
    return pd.read_csv("cleaned_pollution_dataset.csv")

def show_data_overview():

    st.header("Dataset Overview")

    df = load_data()

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Basic Information")
        st.write(f"Number of Records: {df.shape[0]}")
        st.write(f"Number of Features: {df.shape[1]}")
        st.write("Cities Covered:", df["City"].nunique())

    st.subheader("Sample Records")
    st.dataframe(df.head())